---
# 
#
# run
#   ansible-playbook -i inventory-localhost.yml  filter-difference.yml  
#
# My test directory looks like this. 
#

- name: use difference
  hosts: localhost 
  gather_facts: no
  become: no
  connection: local
  vars:
  - a_list_of_files:
    - /dir1/list_me
    - /dir1/dir2/list_me
    - /dir1/dir2/dir5/ignore_me
    - /dir1/dir2/dir4/list_me
    - /dir1/dir3/ignore_me_too
    - /dir1/dir6/list_me
    - /dir1/dir7/and_me
    - /dir1/dir7/list_me/file9
  - files_to_ignore:
    - /dir1/dir2/dir5/ignore_me
    - /dir1/dir3/ignore_me_too
    - /dir1/dir7/and_me
  tasks:

  - name: list files from the first list that are not in the second list. No need for the list filter.
    debug: 
      msg: "{{ a_list_of_files | difference(files_to_ignore) }}"

