---
#
# run
#   ansible-playbook filter-indent.yml
#
# This filter is one of jinja2's builtin filters. 
# Builtin filters are described in the jinja2 docs.
# https://jinja.palletsprojects.com/en/3.0.x/templates/#builtin-filters
# For more information on the template module, see the ansible docs.
# https://docs.ansible.com/ansible/latest/modules/template_module.html
#

- name: indent filter
  hosts: localhost 
  gather_facts: no
  become: no
  connection: local

  vars:
  # The fourth line is indented, but contains no characters. 
  - my_text_block: |
      first line
      second line 
      third line
      
      fifth line

  tasks:
  - name: display in a template 
    template: 
      src: './filter-indent.j2'
      dest: './filter-indent.txt'
 
