---
# upper filter 
#
# run
#   ansible-playbook filter-upper.yml
#
# https://jinja.palletsprojects.com/en/3.0.x/templates/#jinja-filters.upper

- name: upper case
  hosts: localhost 
  gather_facts: no
  become: no
  connection: local
  vars:
  - my_list: 
    - val1!
    - VAL2.
    - "Val3 :-)"
  tasks:

  - name: Change all alphabetic characters in upper case to upper case. Leave the others.
    debug: 
      msg: "list: {{ my_list | upper }}"

