---
# ipaddr filter
# run
#   ansible-playbook filter-ipaddr-more-keywords.yml 
#
# more variations
#
# ipaddr('address')
# ipaddr('network')
# ipaddr('netmask') 
# ipaddr('broadcast') 
# ipaddr('bool') 
#
- name: ipaddr filter
  hosts: localhost 
  gather_facts: no
  become: no
  connection: local
  tasks:

  - name: "keywords (I thought keywords were barewords): host/prefix, network, netmask and broadcast"
    vars: 
      ipv4_host: '1.2.3.4/8'
    debug: 
      msg: "{{ ipv4_host }} translates to host/prefix: {{ ipv4_host | ipaddr('host/prefix') }}, network: {{ ipv4_host | ipaddr('network') }}, netmask: {{ ipv4_host | ipaddr('netmask') }}, broadcast: {{ ipv4_host | ipaddr('broadcast') }}"

  - name: "more keywords: prefix, net"
    vars: 
      ipv4_host: '1.2.3.4/8'
    debug: 
      msg: "{{ ipv4_host }} translates to prefix: {{ ipv4_host | ipaddr('prefix') }}, net: {{ ipv4_host | ipaddr('net') }}"

  - name: "conversions from octets (dotted quads) to decimal, from IPv4 to IPv6"
    vars: 
      ipv4_addr: '1.2.3.4'
    debug: 
      msg: "{{ ipv4_addr }} translates to int: {{ ipv4_addr | ipaddr('int') }}, 6to4: {{ ipv4_addr | ipaddr('6to4') }}"


