---
# contact four hosts
#
# run
# ansible-playbook -i inv-four-hosts-inventory.yml inv-four-hosts.yml
#
# This playbook runs on host1, host2, host3 and host4. 
# Or at least it looks like it does -  we don't really have many machines.
# Connection trickery points all host names to localhost.
# Have a look at the inventory to see the "ansible_connection: local" line.
# For more information, see "Connecting to hosts: behavioral inventory parameters".
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#connecting-to-hosts-behavioral-inventory-parameters
#
- hosts: all
  gather_facts: no
  become: no
  tasks: 

  
  - name: display inventory hostname
    debug: 
      msg: "I am {{ inventory_hostname }}"

