---
# show hostname from inventory
#
# run
# ansible-playbook -i inv-list-inventory.yml inv-list.yml
#
- hosts: all
  gather_facts: no
  become: no
  tasks: 

  
  - name: display inventory hostnames 
    debug: 
      var: inventory_hostname
    delegate_to: localhost
