[ungrouped.hosts.host1]
ansible_connection = "local"
ansible_python_interpreter = "auto_silent"

[ungrouped.hosts.host2]
ansible_connection = "local"
ansible_python_interpreter = "auto_silent"

[ungrouped.hosts.host3]
ansible_connection = "local"
ansible_python_interpreter = "auto_silent"

[ungrouped.hosts.host4]
ansible_connection = "local"
ansible_python_interpreter = "auto_silent"

