---
# A lookup plug-in is an Ansible extension to the Jinja2 templating language. 
# doc
#   ansible-doc -t lookup password
# uses passlib. Passlib is a password hashing library for Python 2 & 3, 
# which provides cross-platform implementations of over 30 password hashing algorithms
# https://passlib.readthedocs.io/en/stable/index.html
# values for 'encrypt=' option are here. 
# passlib.hash - Password Hashing Schemes
# https://passlib.readthedocs.io/en/stable/lib/passlib.hash.html#module-passlib.hash
#
# run
#   ansible-playbook -i inventory-localhost.yml lookup-password.yml
#

- name: 
  hosts: localhost 
  gather_facts: no
  become: no
  connection: local
  tasks:

  - name: users
    set_fact: 
      user_list: 
      - ann
      - ben
      - claire
      - dan

  - name: "create a 9 character password for each user." 
    vars:
      password_file: "{{ 'lookup-password-1-' + item }}"
      password: "{{ lookup('password', '{{ password_file }}' + ' length=9') }}"
    debug:
       msg: "Created password {{ password }} and stored it in file {{ password_file }}"
    loop: "{{ user_list }}"

  - name: "create a password using more types of character, then encrypt it. Store the plain version and salt." 
    vars:
      password_file: "{{ 'lookup-password-2-' + item }}"
      encrypted_password: "{{ lookup('password', '{{ password_file }}' + ' length=9 chars=ascii_letters,digits,hexdigits,punctuation encrypt=sha256_crypt') }}"
    debug:
       msg: "Created encrypted password {{ encrypted_password }} and stored plain text version and salt in file {{ password_file }}"
    loop: "{{ user_list }}"

  - name: "create a password, store the unencrypted version, and encrypt using a filter. "
    vars:
      password_file: "{{ 'lookup-password-3-' + item }}"
      plain_password: "{{ lookup('password', '{{ password_file }}' + ' length=9 ') }}"
      encrypted_password: "{{ plain_password | password_hash('sha512') }}"
    debug:
       msg: "Created password {{ plain_password }}, stored it in file {{ password_file }}, and encrypted it with sha512 hash: {{ encrypted_password }}"
    loop: "{{ user_list }}"
