# view a configuration variable
# run
#  ansible-playbook lookup-config.yml 
# this version changes DEFAULT_MODULE_PATH
#  ANSIBLE_LIBRARY=path1:path2:path3  ansible-playbook lookup-config.yml 
#
# configuration variables
# That ANSIBLE_LIBRARY environment variable tells the playbook where to look for the module.
# This environment variable is used to set one of Ansible's confugration variables.
# Confusingly, the names don't match. 
# The env var is ANSIBLE_LIBRARY and the config var is DEFAULT_MODULE_PATH.
#
# To list all configuration variables, along with their environment variable names, run this.
#   ansible-config list
# In that big list is this entry.
#   DEFAULT_MODULE_PATH:
#     default: ~/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
#     description: Colon separated paths in which Ansible will search for Modules.
#     env:
#     - name: ANSIBLE_LIBRARY
#     ini:
#     - key: library
#       section: defaults
#     name: Modules Path
#     type: pathspec
#

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:

  - name: This is how Ansible set the ANSIBLE_LIBRARY path.
    debug: 
      msg: "DEFAULT_MODULE_PATH: {{ lookup('config', 'DEFAULT_MODULE_PATH')}}"

