---
# dict, a lookup plug-in
# A lookup plug-in is an Ansible extension to the Jinja2 templating language. 
# https://role.rhu.redhat.com/rol-rhu/app/courses/do447-2.8/pages/ch04s03
#
# run
#   ansible-playbook lookup-dict.yml
#

- name: dict, a lookup plugin
  hosts: localhost 
  gather_facts: no
  become: no
  connection: local
  vars:
    users:
      alice:
        name: Alice Appleworth
        telephone: 123-456-7890
      bob:
        name: Bob Bananarama
        telephone: 987-654-3210
  tasks:

    # with predefined vars
    - name: Print phone records
      debug:
        msg: "User {{ item.key }} is {{ item.value.name }} ({{ item.value.telephone }})"
      loop: "{{ lookup('dict', users) }}"

    # with inline dictionary
    - name: show dictionary
      debug:
        msg: "{{item.key}}: {{item.value}}"
      with_dict: {a: 1, b: 2, c: 3}

    # Items from loop can be used in when: statements
    - name: set_fact when alice in key
      set_fact:
        alice_exists: true
      loop: "{{ lookup('dict', users) }}"
      when: "'alice' in item.key"
  
