# The 'pause' module bypasses the host loop.
#
# run
#   ansible-playbook -i inv-four-hosts-inventory.yml module-pause.yml
#

- name: 
  hosts: all
  gather_facts: no
  become: no
  tasks:

  - name: OS pause runs on every machine.
    command: 
      cmd: sleep 1
    changed_when: no


  - name: ansible pause runs once
    pause: 
      seconds: 1


# You can't use pause with strategy: free
# This pause task causes this error.
#  ERROR! The 'pause' module bypasses the host loop, which is currently not supported in the free strategy and would instead execute for every host in the inventory list.
# The default strategy is linear. The first playbook here uses this strategy.
- name: 
  hosts: all
  gather_facts: no
  become: no
  strategy: free
  tasks:

  - debug:
      msg: 'The pause task, combined with "strategy: free", causes an error.' 

  - name: OS pause 
    command: 
      cmd: sleep 1
    changed_when: no

  - name: You see this sentence in the error message. This is the pause task.
    pause: 
      seconds: 1

