---
#
# run
#   ansible-playbook -i inventory-localhost.yml multiline.yml
#

- name: multiline
  hosts: localhost 
  gather_facts: no
  become: no
  connection: local
  # This variable is a block scalar. 
  # It is a literal, which means the pipe | tells ansible to include all special characters.
  # most special characters are safe to include.
  vars:
    text_block: |
        "double quotes" and 'single quotes' are fine.
        So are (round braces). [Square braces] too.
        {curly braces} are OK, but ansible chokes on {\{ double curly braces }\} so they must be escaped.
    test_file_1: /tmp/my-ansible-experiment-1.txt
    test_file_2: /tmp/my-ansible-experiment-2.txt
  tasks:

  # The first couple tasks write this scalar to a file and to the screen.
  # The file will look exactly the same, minus the indent. 
  # The task output will be one line, showing newlines as \n

  - name: "copy the content to {{ test_file_1 }}"
    copy: 
      content: "{{ text_block }}"
      dest: "{{ test_file_1 }}"

  - name: "This is how the variable appears in task output. It's an escaped version of what's in {{ test_file_1 }}"
    debug: 
      msg: "string: '{{ text_block }}'"

  # These tasks display variations of this text block, in the task output. 

  - name: block scalar, literal, chomp. The - after the pipe removes all newlines at the end of the string.
    vars: 
      text_block: |-
        bla bla 
        wibble wibble
        bla bla 
    debug: 
      msg: "string: '{{ text_block }}'"

  # folding
  # https://yaml.org/spec/1.2/spec.html#id2796251

  - name: block scalar, folded. Folded may not mean what you think it means. The > replaces all newlines with spaces. It does not remove extra spaces. 
    vars: 
      text_block: >
        bla    bla 
        wibble wibble
        bla    bla 
    debug: 
      msg: "string: '{{ text_block }}'"

  - name: block scalar, literal, indented. The + after the pipe is supposed to preserve indentation. Doesn't work in Ansible?
    set_fact: 
      text_block_2: |+
        bla bla 
        wibble wibble
        bla bla 

  - name: display doesn't look any different. 
    debug: 
      msg: "string: '{{ text_block_2 }}'"

  - name: "Check {{ test_file_2 }}"
    copy: 
      content: "{{ text_block_2 }}"
      dest: "{{ test_file_2 }}"

