# "tasks" is an anonymous list of tasks
# run
#   ansible-playbook play-tasks.yml
#

- name: a list of tasks
  hosts: localhost
  gather_facts: no
  become: no
  connection: local
  tasks:

  - name: I am the first task.
    debug: 
      msg: Execution starts at the top.

  - name: I am the the second task.
    debug: 
      msg: Hello from the middle

  - name: I am the third task.
    debug: 
      msg: Execution ends at the bottom.

