---
# simple variable 
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#simple-variables
#
# run
#   ansible-playbook var-simple.yml
#
# variable assignment 

- name: define and display a simple variable
  hosts: localhost 
  gather_facts: no
  become: no
  connection: local
  # define the simple variable
  vars:
    simple_variable: I don't have quotes

  tasks:

  - name: display the simple variable content, using a jinja2 substitution 
    debug: 
      msg: "simple_variable: {{ simple_variable }}"

  - name: make another variable that is an exact copy
    vars:
      copy_of_variable: "{{ simple_variable }}"
    debug: 
      msg: "copy_of_variable: {{ simple_variable }}"

