---
# rearrange dictionaries into other dictionaries
# run 
#   ansible-playbook var-dict-to-dict.yml 
#  
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#dictionary-variables
#
#

- name: rearrange dictionaries into lists
  hosts: localhost 
  gather_facts: no
  become: no
  connection: local
  # define dictionary variables
  vars:
    dictionary_variable_1: 
      d1_key_1: d1_value_1
      d1_key_2: d1_value_2
      d1_key_3: d1_value_3
    dictionary_variable_2: 
      d2_key_1: d2_value_1
      d2_key_2: d2_value_2
      d2_key_3: d2_value_3

  tasks:

  - name: combine two dictionaries using filter "combine"
    vars:
      list_of_dicts: "{{ dictionary_variable_1 | combine(dictionary_variable_2) }}"
    debug: 
      msg: "value: {{ list_of_dicts }}"

